name: practice_tdd
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  curl_logger_dio_interceptor: ^0.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_riverpod: ^2.1.3
  get_it: ^7.2.0
  http: ^0.13.5
  injectable: any
  internet_connection_checker: ^1.0.0+1
  mocktail: ^0.3.0
  pretty_dio_logger: ^1.1.1
  riverpod: ^2.1.3
  shared_preferences: ^2.0.17
  state_notifier_test: ^0.0.9

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  injectable_generator: null
  json_serializable: ^6.3.1
  mockito: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
