name: CL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Run unit tests
        run: flutter test --coverage
      - name: Upload to code coverage
        uses: codecov/codecov-action@v1.2.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info